### ISSUE TITLE
Panic runtime error

### ISSUE THREAD

**Issue by Emilien942702** [bureau14/qdb-grafana-plugin#1]
Hello,
I'm trying to run QuasarDB and Grafana together, but I'm getting the following error :

> 2019/06/03 17:06:39 http: panic serving 127.0.0.1:52694: runtime error: invalid memory address or nil pointer dereference
goroutine 221 [running]:
net/http.(*conn).serve.func1(0xc042138be0)
	C:/Go-1.9-64/src/net/http/server.go:1697 +0xd7
panic(0x958200, 0xcf5fc0)
	C:/Go-1.9-64/src/runtime/panic.go:491 +0x291
github.com/bureau14/qdb-api-rest/restapi.configureAPI.func4(0xc04227fbf0, 0xf, 0xd, 0xc0423fd460, 0x16)
	Z:/TeamCity/work/bde77d469d136de3/src/github.com/bureau14/qdb-api-rest/restapi/configure_qdb_api_rest.go:123 +0xf5
github.com/bureau14/qdb-api-rest/restapi/operations.(*QdbAPIRestAPI).AuthenticatorsFor.func1(0xc0423fd460, 0x16, 0x16, 0xc0422f3901, 0x60042124000, 0x10)
	Z:/TeamCity/work/bde77d469d136de3/src/github.com/bureau14/qdb-api-rest/restapi/operations/qdb_api_rest_api.go:216 +0x47
github.com/go-openapi/runtime/security.APIKeyAuth.func3(0xc042124100, 0x3, 0xc04248a000, 0x19a06a8, 0x0, 0x0)
	c:/Go/src/github.com/go-openapi/runtime/security/authenticator.go:164 +0x9b
github.com/go-openapi/runtime/security.HttpAuthenticator.func1(0x90da40, 0xc04245cd60, 0x4129ef, 0x20, 0x0, 0xc0420942c0, 0xc04245cd60)
	c:/Go/src/github.com/go-openapi/runtime/security/authenticator.go:38 +0x6f
github.com/go-openapi/runtime.AuthenticatorFunc.Authenticate(0xc042148c60, 0x90da40, 0xc04245cd60, 0x6, 0xc042094348, 0x1, 0x4, 0xc04248a000)
	c:/Go/src/github.com/go-openapi/runtime/interfaces.go:72 +0x41
github.com/go-openapi/runtime/middleware.(*RouteAuthenticator).Authenticate(0xc0433a67e0, 0xc042124100, 0xc042124000, 0xcc6165, 0x0, 0x0, 0xc0424e1790, 0x5571f7)
	c:/Go/src/github.com/go-openapi/runtime/middleware/router.go:184 +0x1da
github.com/go-openapi/runtime/middleware.RouteAuthenticators.Authenticate(0xc042036cc0, 0x1, 0x1, 0xc042124100, 0xc042124000, 0xc0424e18a8, 0xc04248a000, 0x19a06a8, 0x0, 0xcc6163)
	c:/Go/src/github.com/go-openapi/runtime/middleware/router.go:265 +0x19d
github.com/go-openapi/runtime/middleware.(*Context).Authorize(0xc04249e3f0, 0xc042124100, 0xc042124000, 0xc042124100, 0x959d01, 0xc042124000, 0xc0424a1d80, 0xc04249ef60)
	c:/Go/src/github.com/go-openapi/runtime/middleware/context.go:423 +0x101
github.com/bureau14/qdb-api-rest/restapi/operations/query.(*PostQuery).ServeHTTP(0xc0420c2ae0, 0xcc1360, 0xc042109180, 0xc042124100)
	Z:/TeamCity/work/bde77d469d136de3/src/github.com/bureau14/qdb-api-rest/restapi/operations/query/post_query.go:51 +0xa8
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0xcc1360, 0xc042109180, 0xc042124100)
	c:/Go/src/github.com/go-openapi/runtime/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc0421480b0, 0xcc1360, 0xc042109180, 0xc042124100)
	C:/Go-1.9-64/src/net/http/server.go:1918 +0x4b
github.com/go-openapi/runtime/middleware.NewRouter.func1(0xcc1360, 0xc042109180, 0xc043377f00)
	c:/Go/src/github.com/go-openapi/runtime/middleware/router.go:76 +0x36b
net/http.HandlerFunc.ServeHTTP(0xc0424aab80, 0xcc1360, 0xc042109180, 0xc043377f00)
	C:/Go-1.9-64/src/net/http/server.go:1918 +0x4b
github.com/go-openapi/runtime/middleware.Redoc.func1(0xcc1360, 0xc042109180, 0xc043377f00)
	c:/Go/src/github.com/go-openapi/runtime/middleware/redoc.go:72 +0x9b
net/http.HandlerFunc.ServeHTTP(0xc04226b340, 0xcc1360, 0xc042109180, 0xc043377f00)
	C:/Go-1.9-64/src/net/http/server.go:1918 +0x4b
github.com/go-openapi/runtime/middleware.Spec.func1(0xcc1360, 0xc042109180, 0xc043377f00)
	c:/Go/src/github.com/go-openapi/runtime/middleware/spec.go:46 +0x7a
net/http.HandlerFunc.ServeHTTP(0xc04226b380, 0xcc1360, 0xc042109180, 0xc043377f00)
	C:/Go-1.9-64/src/net/http/server.go:1918 +0x4b
github.com/bureau14/qdb-api-rest/restapi.HTTPSwitchMiddleWare.func1(0xcc1360, 0xc042109180, 0xc043377f00)
	Z:/TeamCity/work/bde77d469d136de3/src/github.com/bureau14/qdb-api-rest/restapi/configure_qdb_api_rest.go:277 +0x1c9
net/http.HandlerFunc.ServeHTTP(0xc042484810, 0xcc1360, 0xc042109180, 0xc043377f00)
	C:/Go-1.9-64/src/net/http/server.go:1918 +0x4b
github.com/rs/cors.(*Cors).Handler.func1(0xcc1360, 0xc042109180, 0xc043377f00)
	c:/Go/src/github.com/rs/cors/cors.go:214 +0x10f
net/http.HandlerFunc.ServeHTTP(0xc0421a8580, 0xcc1360, 0xc042109180, 0xc043377f00)
	C:/Go-1.9-64/src/net/http/server.go:1918 +0x4b
net/http.serverHandler.ServeHTTP(0xc0422d0270, 0xcc1360, 0xc042109180, 0xc043377f00)
	C:/Go-1.9-64/src/net/http/server.go:2619 +0xbb
net/http.(*conn).serve(0xc042138be0, 0xcc1be0, 0xc042417900)
	C:/Go-1.9-64/src/net/http/server.go:1801 +0x724
created by net/http.(*Server).Serve
	C:/Go-1.9-64/src/net/http/server.go:2720 +0x28f

when trying to access the data from grafana (on refresh for example)
I'm running on unsecure QuasarDB 3.3.0, built the plugin with yarn 1.16.0, node 10.16.0 and grafana 6.2.1 
On the web console (grafana side) I have some CORS errors. Might be the reason for the panics, but why do have I some **Z:/TeamCity/work/** in the log ?

Thanks a lot

**Comment by vianneyPL** [comment]
Hi,

Regarding the `Z:/TeamCity/work/`, it seems like there is a forgotten flag during the production build, thanks a lot for catching that one.

For the panic error, could you send me a mail the log of qdb_rest.
If you installed quasardb at the default location, you should find under this path: `C:\Program Files\quasardb\log\qdb_rest.log`

**Comment by Emilien942702** [comment]
link to a paste if the log (regarding the panic error) : [https://paste.ofcode.org/EHjvH9r73cT5DNPQwKXG6z](https://paste.ofcode.org/EHjvH9r73cT5DNPQwKXG6z) 

Thanks a lot

**Comment by vianneyPL** [comment]
Could you provide the query you were trying?

**Comment by Emilien942702** [comment]
`select cno from donnees`
also tried more complex ones, did not work either

**Comment by vianneyPL** [comment]
Could you try `select cno from donnees in $__range` while making sure the grafana time range has some data in it.

**Comment by Emilien942702** [comment]
just tried, same panic errors

**Comment by Emilien942702** [comment]
I tried on another installation (same system) and still get the panic errors.
By the way, I just noticed that launching the qdbd.exe also launches the REST api, so I don't have to launch it separately.

**Comment by vianneyPL** [comment]
We are looking into this issue.
If you have a sample of your dataset it would be perfect to reproduce exactly what you encounter.

**Comment by Emilien942702** [comment]
here is a sample : [https://paste.ofcode.org/xppr6XEULjLGpDjqkwjaVE](https://paste.ofcode.org/xppr6XEULjLGpDjqkwjaVE)
columns 

> quasardb.ColumnInfo(quasardb.ColumnType.Int64, "azimuth"),
           quasardb.ColumnInfo(quasardb.ColumnType.Int64, "cno"),
           quasardb.ColumnInfo(quasardb.ColumnType.Int64, "elevation"),
           quasardb.ColumnInfo(quasardb.ColumnType.Int64, "gnssSystem"),
           quasardb.ColumnInfo(quasardb.ColumnType.Int64, "svid"),
           quasardb.ColumnInfo(quasardb.ColumnType.Int64, "used")

Thanks a lot

**Comment by Emilien942702** [comment]
Fixed by [#2020a59](https://github.com/bureau14/qdb-grafana-plugin/commit/92bf26d4521e631ecd6597e60ba301cb9292f6de)
